### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by thiagopelizoni**
* Generate a random user password instead of null using wp_generate_password();
* When create a new user, instead of use **username@domain.com** as Wordpress user, I changed to be only **username**;
* When authenticate an existent user, it will check **username** instead of **username@domain.com**;
* Replacing tabs for spaces into aad-sso-wordpress.php file;

### CODE REVIEW

**Comment by psignoret** [comment]
Thanks for contributing!

Can you please submit each logically grouped set of changes as an individual pull requests? This will make it easier to review. That said, I've had a look at what you're proposing, and have some comments I can give you already.

Regarding the format/comment changes:

 * You've changed the header format to something which is not the [WordPress plugin header](https://developer.wordpress.org/plugins/the-basics/header-requirements/) format.
 * You've changed the version to something far from the current version.
 * You've changed all the tabs to spaces. WordPress [recommends](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#4-code-must-be-mostly-human-readable) following the [WordPress PHP Coding Standard](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation), which says to use tabs.

Regarding the functionality changes themselves:

 * Is `wp_generate_password()` better than a null password? (I really don't know.)
 * For user provisioning: If you want to propose changing how the users are auto-provisioned, I suggest making it a configurable option. What you're proposing poses a collision risk (there's no guarantee two users in Azure AD will not share the same `unique_name` suffix), which could cause errors (in the best case) or unauthorized access (in the worst case).
 * For matching existing users: The current version of the plugin already offers a configuration option which will match on the user's UPN alias: `match_on_upn_alias`. Did you try that out first?

**Comment by thiagopelizoni** [comment]
Sure, I'll do it!

**Comment by bradkovach** [comment]
@psignoret @thiagopelizoni `null` is generally regarded as a proper way to ensure that the user cannot login via username/password (ie, ensuring that rules enforced by aadsso are not circumvented)

WordPress properly stores passwords as salted hashes, which means that there exists an input that can be used to authenticate using the hash scheme.

On the other hand, when the `password` field is `null`, there is NO input that produces a hash that allows the user to authenticate.  WordPress allows null in the password field on purpose: it disables the default login mechanisms (any attempt to login will fail).

**Comment by bradkovach** [comment]
Also, this PR changes indentation from tabs to spaces.  Please revert this to tabs so we don't overwrite commit history detail.

**Comment by bradkovach** [comment]
+1 to reverting to tabs.  Tabs getting converted to spaces will destroy blame view and detailed commit history.

**Comment by psignoret** [comment]
...also, tabs [are superior](https://www.youtube.com/watch?v=SsoOG6ZeyUI) to spaces. 🤣

**Pull request closed without merging**
