### PR TITLE
Preliminary draft of CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by bradkovach**
Pursuant to #53.

### CODE REVIEW

**Comment by bradkovach** [comment]
I'm done.  Pretty boilerplate, really.  I am unfamiliar with the "internationalization" process, so some instructions from @christianhennen might be helpful!

**Comment by christianhennen** [comment]
Your remarks to the i18n process in Contributing.md are adequate, since everything you need to know is covered by the WordPress help pages. The only thing that needs to be added as soon as the plugin hits the official Plugin Directory, is that there is an automatic translation update mechanism for plugins in said directory :)

**Comment by christianhennen** [comment]
I just noticed you changed the text domain portion of the __ functions to the AADSSO constant. According to the [documentation](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/) this is prohibited:

> Do not use variable names for the text domain portion of a gettext function.  Do not do this as a shortcut: __( ‘Translate me.’ , $text_domain );

**Comment by psignoret** [comment]
I'm not sure a constant counts as a variable, but I'll take a look. (Even if it does, it'll be a simple enough search and replace.) Thanks for the comment! And I'll also look at the translation feature you mention.

**Comment by christianhennen** [comment]
See also here: https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/

**Comment by christianhennen** [comment]
I'll replace the constant with my upcoming translation update.

**Comment by psignoret** [comment]
Sounds great, thanks!

**Pull request merged**
